### ISSUE TITLE
Wrong output text

### ISSUE THREAD

**Issue by Balindil** [Zeichen32/PiwikCustomOptOut#21]
If I "5) Use the iframe code provided below the input fields to add the Piwiki Opt-Out to your website."
the output is:
"CustomOptOut_YouMayOptOut 
 CustomOptOut_YouMayOptOutBis

 CustomOptOut_YouAreOptedIn CustomOptOut_ClickHereToOptOut"
even if I test the output in Piwik.

Piwik 2.11.0 and Custom Opt-Out 0.2.0

**Comment by Zeichen32** [comment]
I can confirm the issue. I am working on it!

**Comment by Zeichen32** [comment]
Fixed for now, but i need to remove the new feature to change the opt-out text. :cry: 

Because of some breaking changes in the new [piwik version](https://github.com/piwik/piwik/blob/master/CHANGELOG.md#piwik-2110) appears this error.

I am searching for a new solution to support this feature again.

**Comment by Zeichen32** [comment]
Can not be fixed anymore, since this plugin just add the stylesheets to the core view.
